# Generated by Django 5.2.1 on 2025-05-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='registered_by',
            field=models.CharField(choices=[('online', 'Online'), ('staff', 'Staff')], default='online', max_length=10),
        ),
    ]
