# Generated by Django 5.2.1 on 2025-05-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_email_patient_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='must_complete_profile',
            field=models.BooleanField(default=True),
        ),
    ]
