# Generated by Django 5.2.1 on 2025-05-23 14:14

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_department_doctor_name_doctor_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('General', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Orthopaedics', 'Orthopaedics'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('MS', 'MS'), ('DM', 'DM'), ('MCH', 'MCH'), ('BDS', 'BDS'), ('MDS', 'MDS')], max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Orthopaedist', 'Orthopaedist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Dermatologist', 'Dermatologist')], max_length=100),
        ),
    ]
