# Generated by Django 5.2.1 on 2025-05-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_department_alter_doctor_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('General Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Orthopaedics', 'Orthopaedics'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Orthopaedist', 'Orthopaedist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Dermatologist', 'Dermatologist')], max_length=100),
        ),
    ]
