# Generated by Django 5.0 on 2025-06-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctoravailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['doctor', 'date', 'start_time']},
        ),
    ]
