# Generated by Django 5.2.1 on 2025-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctoravailability_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='must_reset_password',
            field=models.BooleanField(default=True),
        ),
    ]
