# Generated by Django 5.2.1 on 2025-06-13 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_consultation'),
        ('doctors', '0008_labreferral_prescription_xrayreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_prescription', to='appointments.consultation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor'),
        ),
    ]
